import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSedeIdToUsers1784312351546 implements MigrationInterface {
    name = 'AddSedeIdToUsers1784312351546'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "inplanner"."users" DROP CONSTRAINT "users_area_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."project_responsibles" DROP CONSTRAINT "project_responsibles_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."project_responsibles" DROP CONSTRAINT "project_responsibles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" DROP CONSTRAINT "projects_manager_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."task_assignments" DROP CONSTRAINT "task_assignments_task_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."task_assignments" DROP CONSTRAINT "task_assignments_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" DROP CONSTRAINT "tasks_completed_by_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" DROP CONSTRAINT "tasks_created_by_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" DROP CONSTRAINT "tasks_parent_task_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" DROP CONSTRAINT "tasks_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" DROP CONSTRAINT "notes_created_by_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" DROP CONSTRAINT "notes_task_id_fkey"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_users_area"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_project_resp_user"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_projects_manager"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_projects_sede"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_projects_status"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_projects_priority"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_projects_status_position"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_task_assign_user"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_tasks_project"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_tasks_created_by"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_tasks_parent_task"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_tasks_status"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_tasks_priority"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_notes_task"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_notes_created_by"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ADD "sede_id" uuid`);
        await queryRunner.query(`ALTER TABLE "inplanner"."areas" ALTER COLUMN "estado" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ALTER COLUMN "id_user" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ALTER COLUMN "position" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_tasks_project_status"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "position" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_projects_status_position" ON "inplanner"."projects"  ("position") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_project_status" ON "inplanner"."tasks"  ("project_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_955333ff7758dfad6c897f887b" ON "inplanner"."notes"  ("created_by_id") `);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ADD CONSTRAINT "FK_bb8cbcf3ff9a3a987b63a763139" FOREIGN KEY ("area_id") REFERENCES "inplanner"."areas"("id_area") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."project_responsibles" ADD CONSTRAINT "FK_566e80c6988f8be58e910f10f9e" FOREIGN KEY ("project_id") REFERENCES "inplanner"."projects"("id_project") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."project_responsibles" ADD CONSTRAINT "FK_4e4939468618e7bb22ca325442d" FOREIGN KEY ("user_id") REFERENCES "inplanner"."users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ADD CONSTRAINT "FK_87bd52575ded2be008b89dd7b21" FOREIGN KEY ("manager_id") REFERENCES "inplanner"."users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."task_assignments" ADD CONSTRAINT "FK_b389f4488d0a8241c3c98273966" FOREIGN KEY ("task_id") REFERENCES "inplanner"."tasks"("id_task") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."task_assignments" ADD CONSTRAINT "FK_1673eab025dbc14e188bd4df67c" FOREIGN KEY ("user_id") REFERENCES "inplanner"."users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "inplanner"."projects"("id_project") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ADD CONSTRAINT "FK_54fc42a253a8338488ec1f960ad" FOREIGN KEY ("parent_task_id") REFERENCES "inplanner"."tasks"("id_task") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ADD CONSTRAINT "FK_0804c9432857e4d333583f5afe1" FOREIGN KEY ("created_by_id") REFERENCES "inplanner"."users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ADD CONSTRAINT "FK_5bd5aae9320e3041a2c5084b7cc" FOREIGN KEY ("completed_by_id") REFERENCES "inplanner"."users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ADD CONSTRAINT "FK_89398e8da167f82954f7b8c7d7d" FOREIGN KEY ("task_id") REFERENCES "inplanner"."tasks"("id_task") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ADD CONSTRAINT "FK_955333ff7758dfad6c897f887bb" FOREIGN KEY ("created_by_id") REFERENCES "inplanner"."users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" DROP CONSTRAINT "FK_955333ff7758dfad6c897f887bb"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" DROP CONSTRAINT "FK_89398e8da167f82954f7b8c7d7d"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" DROP CONSTRAINT "FK_5bd5aae9320e3041a2c5084b7cc"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" DROP CONSTRAINT "FK_0804c9432857e4d333583f5afe1"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" DROP CONSTRAINT "FK_54fc42a253a8338488ec1f960ad"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."task_assignments" DROP CONSTRAINT "FK_1673eab025dbc14e188bd4df67c"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."task_assignments" DROP CONSTRAINT "FK_b389f4488d0a8241c3c98273966"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" DROP CONSTRAINT "FK_87bd52575ded2be008b89dd7b21"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."project_responsibles" DROP CONSTRAINT "FK_4e4939468618e7bb22ca325442d"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."project_responsibles" DROP CONSTRAINT "FK_566e80c6988f8be58e910f10f9e"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" DROP CONSTRAINT "FK_bb8cbcf3ff9a3a987b63a763139"`);
        await queryRunner.query(`DROP INDEX "inplanner"."IDX_955333ff7758dfad6c897f887b"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_tasks_project_status"`);
        await queryRunner.query(`DROP INDEX "inplanner"."idx_projects_status_position"`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "position" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_tasks_project_status" ON "inplanner"."tasks" USING btree ("project_id", "status") `);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ALTER COLUMN "position" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ALTER COLUMN "id_user" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "inplanner"."areas" ALTER COLUMN "estado" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" DROP COLUMN "sede_id"`);
        await queryRunner.query(`CREATE INDEX "idx_notes_created_by" ON "inplanner"."notes" USING btree ("created_by_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notes_task" ON "inplanner"."notes" USING btree ("task_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_priority" ON "inplanner"."tasks" USING btree ("priority") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_status" ON "inplanner"."tasks" USING btree ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_parent_task" ON "inplanner"."tasks" USING btree ("parent_task_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_created_by" ON "inplanner"."tasks" USING btree ("created_by_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_project" ON "inplanner"."tasks" USING btree ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_task_assign_user" ON "inplanner"."task_assignments" USING btree ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_status_position" ON "inplanner"."projects" USING btree ("status", "position") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_priority" ON "inplanner"."projects" USING btree ("priority") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_status" ON "inplanner"."projects" USING btree ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_sede" ON "inplanner"."projects" USING btree ("sede_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_manager" ON "inplanner"."projects" USING btree ("manager_id") `);
        await queryRunner.query(`CREATE INDEX "idx_project_resp_user" ON "inplanner"."project_responsibles" USING btree ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_area" ON "inplanner"."users" USING btree ("area_id") `);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ADD CONSTRAINT "notes_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "inplanner"."tasks"("id_task") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."notes" ADD CONSTRAINT "notes_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "inplanner"."users"("id_user") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ADD CONSTRAINT "tasks_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "inplanner"."projects"("id_project") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ADD CONSTRAINT "tasks_parent_task_id_fkey" FOREIGN KEY ("parent_task_id") REFERENCES "inplanner"."tasks"("id_task") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ADD CONSTRAINT "tasks_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "inplanner"."users"("id_user") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."tasks" ADD CONSTRAINT "tasks_completed_by_id_fkey" FOREIGN KEY ("completed_by_id") REFERENCES "inplanner"."users"("id_user") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."task_assignments" ADD CONSTRAINT "task_assignments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "inplanner"."users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."task_assignments" ADD CONSTRAINT "task_assignments_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "inplanner"."tasks"("id_task") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."projects" ADD CONSTRAINT "projects_manager_id_fkey" FOREIGN KEY ("manager_id") REFERENCES "inplanner"."users"("id_user") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."project_responsibles" ADD CONSTRAINT "project_responsibles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "inplanner"."users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."project_responsibles" ADD CONSTRAINT "project_responsibles_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "inplanner"."projects"("id_project") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inplanner"."users" ADD CONSTRAINT "users_area_id_fkey" FOREIGN KEY ("area_id") REFERENCES "inplanner"."areas"("id_area") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
