export const VALIDATION = {
  TEXT_MAX_LENGTH: 100,
  TASK_NAME_MAX_LENGTH: 150,
  PASSWORD_MAX_LENGTH: 255,
  DNI_MAX_LENGTH: 20,

  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MIN_LENGTH_UPDATE: 8,

  PAGE_NUMBER_MIN: 1,
  LIMIT_MIN: 1,
  LIMIT_MIN_TASKS: 0,
  LIMIT_MAX: 100,
  LIMIT_MAX_TASKS: 1000,
} as const;
